// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0uKuB5TjyIvoQ6zBFcUSqAcVkDg4yMPc',
    appId: '1:72339108546:web:0f8326d00680c6c622415b',
    messagingSenderId: '72339108546',
    projectId: 'savemoney-c367a',
    authDomain: 'savemoney-c367a.firebaseapp.com',
    storageBucket: 'savemoney-c367a.appspot.com',
    measurementId: 'G-9VQDKLW799',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD48jywWtVLv4FKHrynojCZFYqe6YQ9Fkc',
    appId: '1:72339108546:android:a881c4e994737e5f22415b',
    messagingSenderId: '72339108546',
    projectId: 'savemoney-c367a',
    storageBucket: 'savemoney-c367a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbeBR1pBmFv6-lzLSMlwMHruqq7M7gHnc',
    appId: '1:72339108546:ios:e0e5eaccaa1d37b722415b',
    messagingSenderId: '72339108546',
    projectId: 'savemoney-c367a',
    storageBucket: 'savemoney-c367a.appspot.com',
    iosBundleId: 'com.tung.savemoney.saveMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbeBR1pBmFv6-lzLSMlwMHruqq7M7gHnc',
    appId: '1:72339108546:ios:e0e5eaccaa1d37b722415b',
    messagingSenderId: '72339108546',
    projectId: 'savemoney-c367a',
    storageBucket: 'savemoney-c367a.appspot.com',
    iosBundleId: 'com.tung.savemoney.saveMoney',
  );
}
